version: '3'

services:
  db:
    image: postgres:15.3
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

volumes:
  db_data:
