name: ghcr.io push

on:
  push:
    branches:
      - main

permissions:
  packages: write
  contents: read

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - uses: docker/metadata-action@v4
        id: docker-metadata
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha
            type=sha,format=long

      - uses: docker/build-push-action@v4
        with:
          context: .
          target: production
          push: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
          tags: ${{ steps.docker-metadata.outputs.tags }}
          labels: ${{ steps.docker-metadata.outputs.labels }}
